### ISSUE TITLE
installation requires unzip to be installed

### ISSUE THREAD

**Issue by Firestar-Reimu** [jamespfennell/mathtime-installer#4]
line 283: `echo "Error: installation requires zip to be installed."`

should be changed to unzip

some distributions like archlinux pack zip and unzip as 2 packages.

also, support for other unzip softwares such as KDE Ark and GNOME Archive Manager

**Comment by jamespfennell** [comment]
If you really feel strongly about this I would accept a PR; otherwise, going to close.
