### ISSUE TITLE
Fix copying contents of the CTAN's version

### ISSUE THREAD

**Issue by wojtask** [jamespfennell/mathtime-installer#6]
If the fonts were acquired from https://ctan.org/pkg/mtp2lite?lang=en, the script doesn't work as expected, since the CTAN's .zip archive has an extra top-level directory `mtp2lite`. What worked for me was modifying the `cp` command after the archive got unzipped to:
```bash
sudo cp -r ${TEMPDIR}/mtp2lite/texmf/* ${TEXMF}/
```

However, I'd expect this dummy fix will break the installation of the official font from PCTeX website.

**Comment by jamespfennell** [comment]
Thanks for this info! I imagine there's some magic bash command that would work for both? Like check for the top level directory and cd in if it exists. Honestly at this point I am a little nervous about me making changes to the script because I just really lack the knowledge.

**Comment by wojtask** [comment]
If I find some free time soon, I'll try to come up with a universal
solution and will send you a pull request.
